name: NexusInventoryRankUP
main: br.com.nexus.inventory.Main
version: 1.0.0
commands:
  warp:
    aliases:
      - ir
      - warp
  celeiro:
  hall:
  pesqueiro:
  arena:
  loja:
  kit:
    aliases: kits
  yt:
  youtube:
  discord:
